### PR TITLE
Revert "Function argument changes"

### PR DESCRIPTION
**Pull request by jwbishop**
Reverts uafgeotools/lts_array#4

### CODE REVIEW

**Comment by davidfee5** [comment]
Sorry, I'm a bit lost here. What is being reverted and why?

**Comment by jwbishop** [comment]
> Sorry, I'm a bit lost here. What is being reverted and why?

A change was requested in #4 that wasn't incorporated.

**Comment by davidfee5** [comment]
OK, now I see. Should be close to ready then!

**Review by davidfee5 — APPROVED** [review]

**Comment by liamtoney** [comment]
Oh, I see what's going on. @jwbishop is reverting the previous PR in order to re-merge it with the additional file changes.

I'd say you wouldn't need to request our review on this reversion, but rather the revised PR with the additional changes.

**Review by liamtoney — APPROVED** [review]

**Pull request merged**
